### ISSUE TITLE
GlobalDeviceLimit not work 全局设备限制不生效 v0.8.7

### ISSUE THREAD

**Issue by uvian** [XrayR-project/XrayR#156]
I upgraded XrayR to v0.8.7. After modifying according to the new sample configuration file, I found that GlobalDeviceLimit did not take effect.

The config
node1
```
    PanelType: "V2board"
....
      DeviceLimit: 1
....
      GlobalDeviceLimitConfig:
        Enable: true 
        RedisAddr: redis.com:6379 
        RedisPassword: passwd 
        RedisDB: 1 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)
```
node2
```
    PanelType: "V2board"
....
      DeviceLimit: 1
....
      GlobalDeviceLimitConfig:
        Enable: true 
        RedisAddr: redis.com:6379 
        RedisPassword: passwd 
        RedisDB: 1 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)
```
I tried putting them in the same or different redis DB, but the result is the same

With such a configuration, the device limit will only take effect when two different ips connect to the same node, and if two different ips connect to different nodes, then they can connect normally without being limited.

And I check the redis
```
redis.com:6379> select 1
redis.com:6379[1]> keys *
.....
1) "V2ray_127.0.0.1_54443|3be95056-b059-4b27-a83d-76e558784xxx@v2board.user|1"
2) "1|3be95056-b059-4b27-a83d-76e558784xxx@v2board.user|1"
.....
redis.com:6379[1]> get V2ray_127.0.0.1_54443|3be95056-b059-4b27-a83d-76e558784xxx@v2board.user|1
"\x82\xab1.1.1.1\xd3\x00\x00\x00\x00\x00\x00\x00`\xad2.2.2.2\xd3\x00\x00\x00\x00\x00\x00\x00`"
redis.com:6379[1]> get 1|3be95056-b059-4b27-a83d-76e558784xxx@v2board.user|1
"\x81\xab1.1.1.1\xd3\x00\x00\x00\x00\x00\x00\x00`"
```
The different IPs of my two different devices appear in the key, but any one of the IPs can connect to different node to online at the same time.

Please check if this is a problem with my configuration, thanks.
