### ISSUE TITLE
 vendor preset: disabled

### ISSUE THREAD

**Issue by binad2022** [XrayR-project/XrayR#180]
XrayR.service - XrayR Service
   Loaded: loaded (/etc/systemd/system/XrayR.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2022-12-25 21:22:22 CST; 17min ago
 Main PID: 282362 (XrayR)
    Tasks: 6 (limit: 5817)
   Memory: 31.3M
   CGroup: /system.slice/XrayR.service
           └─282362 /usr/local/XrayR/XrayR -config /etc/XrayR/config.yml

我 真的是崩溃，折腾了两个月，节点一直是黄色的，什么防火墙都关了，就是连不上，教程我都翻烂了，tg群也加了无数次都不给进去

**Comment by binad2022** [comment]
Dec 25 21:30:31 nxacloud-fqcomttn.com XrayR[282362]: 2022/12/25 21:30:31 [http://nf.010****.xyz] V2ray(ID=1) 0 user deleted, 0 user added
Dec 25 21:31:31 nxacloud-fqcomttn.com XrayR[282362]: 2022/12/25 21:31:31 [http://nf.010****..xyz] V2ray(ID=1) 0 user deleted, 0 user added
Dec 25 21:32:32 nxacloud-fqcomttn.com XrayR[282362]: 2022/12/25 21:32:32 [http://nf.010****.xyz] V2ray(ID=1) 0 user deleted, 0 user added
Dec 25 21:33:33 nxacloud-fqcomttn.com XrayR[282362]: 2022/12/25 21:33:33 [http://nf.010****..xyz] V2ray(ID=1) 0 user deleted, 0 user added
Dec 25 21:34:34 nxacloud-fqcomttn.com XrayR[282362]: 2022/12/25 21:34:34 [http://nf.010****..xyz] V2ray(ID=1) 0 user deleted, 0 user added
Dec 25 21:35:36 nxacloud-fqcomttn.com XrayR[282362]: 2022/12/25 21:35:36 [http://nf.010****..xyz] V2ray(ID=1) 0 user deleted, 0 user added
Dec 25 21:36:36 nxacloud-fqcomttn.com XrayR[282362]: 2022/12/25 21:36:36 [http://nf.010****..xyz] V2ray(ID=1) 0 user deleted, 0 user added
Dec 25 21:37:37 nxacloud-fqcomttn.com XrayR[282362]: 2022/12/25 21:37:37 [http://nf.010****..xyz] V2ray(ID=1) 0 user deleted, 0 user added
Dec 25 21:38:39 nxacloud-fqcomttn.com XrayR[282362]: 2022/12/25 21:38:39 [http://nf.010****..xyz] V2ray(ID=1) 0 user deleted, 0 user added
Dec 25 21:39:40 nxacloud-fqcomttn.com XrayR[282362]: 2022/12/25 21:39:40 [http://nf.010****..xyz] V2ray(ID=1) 0 user deleted, 0 user added

**Comment by binad2022** [comment]
我都不知道我到底是漏装了什么，v2那边也都配置， 就是节点一直黄色的，连不上

**Comment by thank243** [comment]
Could you provide more logs and config.yml?

**Comment by binad2022** [comment]
Nodes:

  -
    PanelType: "NewV2board" # Panel type: SSpanel, V2board, PMpanel, Proxypanel, V2RaySocks
    ApiConfig:
      ApiHost: "http://nf.010****.xyz"
      ApiKey: "1******1"
      NodeID: 2
      NodeType: Shadowsocks # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: true # Enable Vless for V2ray Type
      EnableXTLS: true # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
      GlobalDeviceLimitConfig:
        Limit: 0 # The global device limit of a user, 0 means disable
        RedisAddr: 127.0.0.1:6379 # The redis server address
        RedisPassword: YOUR PASSWORD # Redis password
        RedisDB: 0 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        -
          SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: /etc/XrayR/cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: /etc/XrayR/cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb

**Comment by binad2022** [comment]
error.log
2022/12/26 21:30:41 [Info] app/dns: DNS: created localhost client
2022/12/26 21:30:41 [Warning] core: Xray 1.6.6 started
2022/12/26 21:30:42 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:11254
2022/12/26 21:30:42 [Info] transport/internet/udp: listening UDP on 0.0.0.0:11254

**Comment by binad2022** [comment]
我尝试过V2ray, Shadowsocks, Trojan 都是一样

两边v2b和xrayR的防火墙都是关闭的，centos7.x系统

**Comment by binad2022** [comment]
这是我刚重启完xrayR的日志，当前有一个注册的用户，用v2rayNG订阅链接，连接一直是io:read/write on closed pipe
12月 26 21:30:41 VM-741W9P0WB6AE.local systemd[1]: Stopping XrayR Service...
12月 26 21:30:41 VM-741W9P0WB6AE.local systemd[1]: Stopped XrayR Service.
12月 26 21:30:41 VM-741W9P0WB6AE.local systemd[1]: Started XrayR Service.
12月 26 21:30:41 VM-741W9P0WB6AE.local XrayR[23844]: XrayR 0.8.8 (A Xray backend that supports many panels)
12月 26 21:30:41 VM-741W9P0WB6AE.local XrayR[23844]: 2022/12/26 21:30:41 Start the panel..
12月 26 21:30:41 VM-741W9P0WB6AE.local XrayR[23844]: 2022/12/26 21:30:41 Xray Core Version: 1.6.6
12月 26 21:30:42 VM-741W9P0WB6AE.local XrayR[23844]: 2022/12/26 21:30:42 [http://nf.010****.xyz] Shadowsocks(ID=2) Added 1 new users
12月 26 21:30:42 VM-741W9P0WB6AE.local XrayR[23844]: 2022/12/26 21:30:42 [http://nf.010****.xyz] Shadowsocks(ID=2) Start node monitor periodic task
12月 26 21:30:42 VM-741W9P0WB6AE.local XrayR[23844]: 2022/12/26 21:30:42 [http://nf.010****.xyz] Shadowsocks(ID=2) Start user monitor periodic task
12月 26 21:31:43 VM-741W9P0WB6AE.local XrayR[23844]: 2022/12/26 21:31:43 [http://nf.010****.xyz] Shadowsocks(ID=2) 0 user deleted, 0 user added
12月 26 21:32:44 VM-741W9P0WB6AE.local XrayR[23844]: 2022/12/26 21:32:44 [http://nf.010****.xyz] Shadowsocks(ID=2) 0 user deleted, 0 user added
12月 26 21:33:45 VM-741W9P0WB6AE.local XrayR[23844]: 2022/12/26 21:33:45 [http://nf.010****..xyz] Shadowsocks(ID=2) 0 user deleted, 0 user added
12月 26 21:34:46 VM-741W9P0WB6AE.local XrayR[23844]: 2022/12/26 21:34:46 [http://nf.010****.xyz] Shadowsocks(ID=2) 0 user deleted, 0 user added
12月 26 21:35:47 VM-741W9P0WB6AE.local XrayR[23844]: 2022/12/26 21:35:47 [http://nf.010****.xyz] Shadowsocks(ID=2) 0 user deleted, 0 user added
12月 26 21:36:48 VM-741W9P0WB6AE.local XrayR[23844]: 2022/12/26 21:36:48 [http://nf.010****.xyz] Shadowsocks(ID=2) 0 user deleted, 0 user added
12月 26 21:37:49 VM-741W9P0WB6AE.local XrayR[23844]: 2022/12/26 21:37:49 [http://nf.010****.xyz] Shadowsocks(ID=2) 0 user deleted, 0 user added

**Comment by thank243** [comment]
After started up xrayr. Goto `port.ping.pe` to test port is open. BTW turn debug loglevel.

**Comment by binad2022** [comment]
服务端口能通，但是连接端口不通，日志已改为debug模式，但是没有更新的日志

**Comment by binad2022** [comment]
服务端口能通，但是连接端口不通，日志已改为debug模式，但是没有更新的日志

**Comment by binad2022** [comment]
access.log自从上次最后一次重装之后 就没有记录了

2022/12/11 04:33:17 223.104.41.2:16299 rejected  proxy/vless/encoding: invalid request version
2022/12/11 04:33:22 223.104.41.2:16300 rejected  proxy/vless/encoding: invalid request version
2022/12/11 04:33:30 223.104.41.2:16301 rejected  proxy/vless/encoding: invalid request version
2022/12/11 04:33:34 223.104.41.2:16302 rejected  proxy/vless/encoding: invalid request version
2022/12/11 04:33:35 223.104.41.2:16303 rejected  proxy/vless/encoding: invalid request version
2022/12/11 04:33:39 223.104.41.2:16304 rejected  proxy/vless/encoding: invalid request version
2022/12/11 04:33:40 223.104.41.2:16305 rejected  proxy/vless/encoding: invalid request version
2022/12/11 04:33:44 223.104.41.2:16306 rejected  proxy/vless/encoding: invalid request version
2022/12/11 04:33:53 223.104.41.2:16307 rejected  proxy/vless/encoding: invalid request version
2022/12/11 04:33:57 223.104.41.2:16992 rejected  proxy/vless/encoding: invalid request version
2022/12/11 04:33:58 223.104.41.2:16993 rejected  proxy/vless/encoding: invalid request version
2022/12/11 04:34:02 223.104.41.2:16994 rejected  proxy/vless/encoding: invalid request version
2022/12/11 04:34:03 223.104.41.2:16995 rejected  proxy/vless/encoding: invalid request version
2022/12/11 04:34:07 223.104.41.2:16996 rejected  proxy/vless/encoding: invalid request version

**Comment by binad2022** [comment]
服务端口能通，但是连接端口不通，日志已改为debug模式

2022/12/26 23:00:17 [Info] [2676903703] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:17 [Info] [2676903703] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [334288649] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [334288649] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [987463981] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [987463981] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [2335717816] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [2335717816] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [1539263504] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [1539263504] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [1710747154] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [1710747154] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [2461999845] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [2461999845] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [3526488224] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [3526488224] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [1322654019] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [1322654019] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [503952551] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [503952551] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [2132180836] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [2132180836] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [2570017126] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [2570017126] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [1074057584] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [1074057584] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [3631234231] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [3631234231] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [3238200906] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [3238200906] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [4168277600] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [4168277600] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [347050371] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [347050371] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [2536736573] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [2536736573] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [1971338348] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [1971338348] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [3830736767] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [3830736767] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [3385773312] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [3385773312] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [1648563307] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [1648563307] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [1444847409] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [1444847409] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [2828409826] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [2828409826] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [3876913105] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [3876913105] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [1711666742] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [1711666742] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [906264162] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [906264162] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [335374320] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [335374320] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [1925308497] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [1925308497] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [4001348975] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [4001348975] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [2893003717] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [2893003717] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [2107312071] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [2107312071] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [559106894] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [559106894] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [794604420] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [794604420] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [2460208938] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [2460208938] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [1146150078] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [1146150078] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [204076148] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [204076148] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [2241058566] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [2241058566] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [2185711279] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [2185711279] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [1761191851] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [1761191851] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [536599461] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [536599461] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:18 [Info] [2490446744] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:18 [Info] [2490446744] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:19 [Info] [1609467504] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:19 [Info] [1609467504] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
2022/12/26 23:00:19 [Info] [1900369679] proxy/vless/inbound: firstLen = 0
2022/12/26 23:00:19 [Info] [1900369679] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF

**Comment by thank243** [comment]
v2board didn't support vless.

**Comment by binad2022** [comment]
2022/12/26 23:26:47 [Info] [2982523843] app/proxyman/inbound: connection ends > proxy/shadowsocks: failed to create request from: 39.106.209.134:46080 > common/drain: common/drain: unable to drain connection > read tcp 10.0.235.2:11254->39.106.209.134:46080: i/o timeout > proxy/shadowsocks: failed to read 50 bytes > read tcp 10.0.235.2:11254->39.106.209.134:46080: i/o timeout
2022/12/26 23:26:47 [Info] [3362501051] app/proxyman/inbound: connection ends > proxy/shadowsocks: failed to create request from: 117.28.245.235:58504 > common/drain: common/drain: unable to drain connection > read tcp 10.0.235.2:11254->117.28.245.235:58504: i/o timeout > proxy/shadowsocks: failed to read 50 bytes > read tcp 10.0.235.2:11254->117.28.245.235:58504: i/o timeout
2022/12/26 23:26:47 [Info] [2289681295] app/proxyman/inbound: connection ends > proxy/shadowsocks: failed to create request from: 120.195.6.148:44496 > common/drain: common/drain: unable to drain connection > read tcp 10.0.235.2:11254->120.195.6.148:44496: i/o timeout > proxy/shadowsocks: failed to read 50 bytes > read tcp 10.0.235.2:11254->120.195.6.148:44496: i/o timeout
2022/12/26 23:26:49 [Info] [2885782111] app/proxyman/inbound: connection ends > proxy/shadowsocks: failed to create request from: 112.85.231.135:39840 > common/drain: common/drain: unable to drain connection > read tcp 10.0.235.2:11254->112.85.231.135:39840: i/o timeout > proxy/shadowsocks: failed to read 50 bytes > read tcp 10.0.235.2:11254->112.85.231.135:39840: i/o timeout

我用了ss还是一样的情况

**Comment by thank243** [comment]
Can you paste completed `config.yml` on gist? Don't mask datas.

**Comment by binad2022** [comment]
Log:
  Level: debug # Log level: none, error, warning, info, debug 
  AccessPath: # /etc/XrayR/access.Log
  ErrorPath: # /etc/XrayR/error.log
DnsConfigPath: # /etc/XrayR/dns.json # Path to dns config, check https://xtls.github.io/config/dns.html for help
RouteConfigPath: # /etc/XrayR/route.json # Path to route config, check https://xtls.github.io/config/routing.html for help
InboundConfigPath: # /etc/XrayR/custom_inbound.json # Path to custom inbound config, check https://xtls.github.io/config/inbound.html for help
OutboundConfigPath: # /etc/XrayR/custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/outbound.html for help
ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB
Nodes:
  -
  
    PanelType: "NewV2board" # Panel type: SSpanel, V2board, PMpanel, Proxypanel, V2RaySocks
    ApiConfig:
      ApiHost: "http://nf.0101989.xyz"
      ApiKey: "123456789QWERTYU"
      NodeID: 3
      NodeType: Shadowsocks # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: true # Enable Vless for V2ray Type
      EnableXTLS: true # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
      GlobalDeviceLimitConfig:
        Limit: 0 # The global device limit of a user, 0 means disable
        RedisAddr: 127.0.0.1:6379 # The redis server address
        RedisPassword: YOUR PASSWORD # Redis password
        RedisDB: 0 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        -
          SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: /etc/XrayR/cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: /etc/XrayR/cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb

**Comment by binad2022** [comment]
如果你方便的话 我可以把服务器的账号/密码发给你。。我是实在不知道该如何办了

**Comment by thank243** [comment]
```
Log:
  Level: debug # Log level: none, error, warning, info, debug
  AccessPath: # /etc/XrayR/access.Log
  ErrorPath: # /etc/XrayR/error.log
DnsConfigPath: # /etc/XrayR/dns.json # Path to dns config, check https://xtls.github.io/config/dns.html for help
RouteConfigPath: # /etc/XrayR/route.json # Path to route config, check https://xtls.github.io/config/routing.html for help
InboundConfigPath: # /etc/XrayR/custom_inbound.json # Path to custom inbound config, check https://xtls.github.io/config/inbound.html for help
OutboundConfigPath: # /etc/XrayR/custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/outbound.html for help
ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB
Nodes:
  -
    PanelType: "NewV2board" # Panel type: SSpanel, V2board, NewV2board, PMpanel, Proxypanel, V2RaySocks
    ApiConfig:
      ApiHost: "http://nf.0101989.xyz"
      ApiKey: "123456789QWERTYU"
      NodeID: 3
      NodeType: Shadowsocks # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      EnableXTLS: false # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
      GlobalDeviceLimitConfig:
        Enable: false # Enable the global device limit of a user
        RedisAddr: 127.0.0.1:6379 # The redis server address
        RedisPassword: YOUR PASSWORD # Redis password
        RedisDB: 0 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        -
          SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: /etc/XrayR/cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: /etc/XrayR/cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb
  # -
  #   PanelType: "NewV2board" # Panel type: SSpanel, V2board, NewV2board, PMpanel, Proxypanel, V2RaySocks
  #   ApiConfig:
  #     ApiHost: "http://127.0.0.1:668"
  #     ApiKey: "123"
  #     NodeID: 4
  #     NodeType: Shadowsocks # Node type: V2ray, Shadowsocks, Trojan
  #     Timeout: 30 # Timeout for the api request
  #     EnableVless: false # Enable Vless for V2ray Type
  #     EnableXTLS: false # Enable XTLS for V2ray and Trojan
  #     SpeedLimit: 0 # Mbps, Local settings will replace remote settings
  #     DeviceLimit: 0 # Local settings will replace remote settings
  #   ControllerConfig:
  #     ListenIP: 0.0.0.0 # IP address you want to listen
  #     UpdatePeriodic: 10 # Time to update the nodeinfo, how many sec.
  #     EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
  #     CertConfig:
  #       CertMode: dns # Option about how to get certificate: none, file, http, dns
  #       CertDomain: "node1.test.com" # Domain to cert
  #       CertFile: /etc/XrayR/cert/node1.test.com.cert # Provided if the CertMode is file
  #       KeyFile: /etc/XrayR/cert/node1.test.com.pem
  #       Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
  #       Email: test@me.com
  #       DNSEnv: # DNS ENV option used by DNS provider
  #         ALICLOUD_ACCESS_KEY: aaa
  #         ALICLOUD_SECRET_KEY: bbb
```
Use this config and this verison https://github.com/XrayR-project/XrayR/suites/10068600111/artifacts/490278184
