### ISSUE TITLE
invalid memory address or nil pointer dereference !!!

### ISSUE THREAD

**Issue by MrVb0** [XrayR-project/XrayR#204]
Hello
I use XRAYR and V2BOARD
But the connection is disconnected every few seconds, and when I saw the log, I noticed this error :
![xrayr-bug](https://user-images.githubusercontent.com/117315263/211208536-efb2061c-90a7-45ba-9fc4-1eff24a1af35.png)

Please help me to solve the problem

**Comment by thank243** [comment]
Cannot recall, could you provide the condition and config.yml?

**Comment by MrVb0** [comment]
In config.yml everything is normal
I have this problem on almost every 10 servers I have, along with many disconnections
It disconnects every few minutes and connects after a few seconds
It is a boring situation
Could this problem be related to v2board?

**Comment by MrVb0** [comment]
Hello, yes, I have created a separate server for Redis and connected all servers to one Redis server

**Comment by MrVb0** [comment]
Thank you for your reply. So I will wait for the new update.

**Comment by mokhtarabadi** [comment]
I have the same problem, but GlobalDeviceLimitConfig is disabled.
I used PMPanel, ProxyProtocol, Nginx stream, and Trojan
I edited pmpanel.go to add support for ws and h2

**Comment by mokhtarabadi** [comment]
@pocketW if you need tell me I will share my server details so you can check it, I have about 500 active users and now they have bad experience with panel, I think this is emergency bug

**Comment by thank243** [comment]
> > @pocketW if you need tell me I will share my server details so you can check it, I have about 500 active users and now they have bad experience with panel, I think this is emergency bug
> 
> Hi, sorry for the inconvenience. Please kindly provide the configuration file and log if possible. Besides, could you also try to use the old version to see if the problem still exists? You can install the old version by using `XrayR install v0.x.x`.

I think it could happen in this case, due to some reason the UDP conn has closed, But the dispatcher still xfer the traffic to the UDP conn.

**Comment by mokhtarabadi** [comment]
> > @pocketW if you need tell me I will share my server details so you can check it, I have about 500 active users and now they have bad experience with panel, I think this is emergency bug
> 
> Hi, sorry for the inconvenience. Please kindly provide the configuration file and log if possible. Besides, could you also try to use the old version to see if the problem still exists? You can install the old version by using `XrayR install v0.x.x`.

I first used the master branch, and I encounter the bug (also enabling/disabling global device limit not affected)

systems logs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x93de20]
goroutine 21532 [running]:
github.com/xtls/xray-core/transport/internet/udp.(*Dispatcher).Dispatch(0xc00138b980?, {0x3690098, 0xc001219500}, {{0x36921d8?, 0xc000a33670?}, 0xb8c0?, 0xc0?}, 0xc0012194d0)
        github.com/xtls/xray-core@v1.7.2/transport/internet/udp/dispatcher.go:86 +0x1e0
github.com/xtls/xray-core/proxy/trojan.(*Server).handleUDPPayload(0xc001530d50, {0x3690098, 0xc0012d5e90}, 0x0?, 0xc001219440, {0x3694540?, 0xc0014e9ad0})
        github.com/xtls/xray-core@v1.7.2/proxy/trojan/server.go:335 +0x5cb
github.com/xtls/xray-core/proxy/trojan.(*Server).Process(0xc001530d50, {0x3690098, 0xc0012d5e90}, 0x36498d8?, {0x36a00a8?, 0xc0012d5da0}, {0x3694540, 0xc0014e9ad0})
        github.com/xtls/xray-core@v1.7.2/proxy/trojan/server.go:235 +0x1b0d
github.com/xtls/xray-core/app/proxyman/inbound.(*tcpWorker).callback(0xc0014ef7c0, {0x36a00a8, 0xc0012d5da0})
        github.com/xtls/xray-core@v1.7.2/app/proxyman/inbound/worker.go:107 +0x6c3
created by github.com/xtls/xray-core/app/proxyman/inbound.(*tcpWorker).Start.func1
        github.com/xtls/xray-core@v1.7.2/app/proxyman/inbound/worker.go:121 +0x98
xrayr.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
xrayr.service: Failed with result 'exit-code'.
xrayr.service: Scheduled restart job, restart counter is at 14.
```

my config:
```yaml
Log:
  Level: warning # Log level: none, error, warning, info, debug
  AccessPath: /opt/XrayR/logs/access.log
  ErrorPath: /opt/XrayR/logs/error.log

DnsConfigPath: /opt/XrayR/config/dns.json # Path to dns config, check https://xtls.github.io/config/dns.html for help
RouteConfigPath: /opt/XrayR/config/route.json # Path to route config, check https://xtls.github.io/config/routing.html for help
InboundConfigPath: # /opt/XrayR/config/custom_inbound.json # Path to custom inbound config, check https://xtls.github.io/config/inbound.html for help
OutboundConfigPath: /opt/XrayR/config/custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/outbound.html for help

ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB

Nodes:
  - PanelType: "PMpanel" # Panel type: SSpanel, V2board, NewV2board, PMpanel, Proxypanel, V2RaySocks

    ApiConfig:
      ApiHost: https://example.org/webapi
      ApiKey: 123456
      NodeID: 1
      NodeType: Trojan # Node type: V2ray, Shadowsocks, Trojan
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      EnableXTLS: false # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings
      DeviceLimit: 0 # Local settings will replace remote settings
      RuleListPath: /opt/XrayR/config/rulelist # Path to local rulelist file

    ControllerConfig:
      ListenIP: 127.0.0.1 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 10 # Time to update the nodeinfo, how many sec.
      EnableDNS: true # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      DisableUploadTraffic: false # Disable Upload Traffic to the panel
      DisableGetRule: false # Disable Get Rule from the panel
      DisableIVCheck: false # Disable the anti-reply protection for Shadowsocks
      DisableSniffing: false # Disable domain sniffing
      EnableProxyProtocol: true # Only works for WebSocket and TCP

      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)

      GlobalDeviceLimitConfig:
        Enable: true # Enable the global device limit of a user
        RedisAddr: 1.1.1.1:6379 # The redis server address
        RedisPassword: 123456 # Redis password
        RedisDB: 0 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)

      EnableFallback: true # Only support for Trojan and Vless
      FallBackConfigs: # Support multiple fallbacks
        - SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/fallback/ for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable

      CertConfig:
        CertMode: none # Option about how to get certificate: none, file, http, dns
        RejectUnknownSni: false # Reject unknown SNI
        CertDomain: uk1.example.org # Domain to cert (fill in if want xrary issue certificate)
        CertFile: /opt/certificates/xrayr.crt # Provided if the CertMode is file
        KeyFile: /opt/certificates/xrayr.key
        Provider: cloudflare # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: mmokhtarabadi@gmail.com

        DNSEnv: # DNS ENV option used by DNS provider
          CLOUDFLARE_EMAIL: 123456789@gmail.com
          CLOUDFLARE_API_KEY: api_key_here
```

the problem does not appear in version [v0.8.3](https://github.com/XrayR-project/XrayR/tree/b37705b374520d7a73b909c8161e8fbb3870d1cb) 

I think this is xtls bug
