### ISSUE TITLE
V2Board "server is not exist" with Vless node

### ISSUE THREAD

**Issue by JobberRT** [XrayR-project/XrayR#598]
Found a similiar issue here: #527 , but that issue didn't provide detailed info.

# Xrayr Vesion
v0.9.1 and v0.9.2 from install script

# Xrayr Config(Only the important part)
```yaml
Nodes:
  -
    PanelType: "NewV2board" # Panel type: SSpanel, NewV2board, V2board, PMpanel, Proxypanel
    ApiConfig:
      ApiHost: "https://xxx.com"
      ApiKey: "abcd1234"
      NodeID: 6
      NodeType: "V2ray" # Node type: V2ray, Trojan, Shadowsocks, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: true # Enable Vless for V2ray Type
```

# Behavior
executable from install script failed to recognize vless type for V2Board. From code we can see if `apiConfig.NodeType` is `true`, then the url param `node_type` will be `vless`, otherwise `v2ray`.
https://github.com/XrayR-project/XrayR/blob/561f317e243b56921929a0576d09e6ba61cb52d0/api/newV2board/v2board.go#L61-L65

Using the config above, Xrayr from install script failed to recognize `vless` and using `v2ray` as `node_type`, screenshot from nginx access log.
![image](https://github.com/XrayR-project/XrayR/assets/17498767/dd928823-5249-45e5-827e-12c3ea8ca030)

But cloning the repo and build Xrayr in local(macOS M1), and run with the same config file will have a correct `node_type` and sucessfully get the server info from V2Board, screenshot from FiddlerEverywhere and add `client.SetProxy("http://localhost:8866")` to the code.
![image](https://github.com/XrayR-project/XrayR/assets/17498767/0dcf3b52-29be-4f2f-8b43-39d0c451bb2c)
