### ISSUE TITLE
更新 v2board 1.5.5 dev 后 节点掉线

### ISSUE THREAD

**Issue by aiastia** [XrayR-project/XrayR#94]
2022/01/07 19:26:32 convert TransportProtocol failed: infra/conf: Config: unknown transport protocol: 
xrayr_1  | panic: convert TransportProtocol failed: infra/conf: Config: unknown transport protocol: 
xrayr_1  | 
xrayr_1  | goroutine 1 [running]:
xrayr_1  | log.Panic({0xc00081fd78, 0xc000767ba0, 0x7fc3b32a7e30})
xrayr_1  |   log/log.go:354 +0x65
xrayr_1  | github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc0005c8f30)
xrayr_1  |   github.com/XrayR-project/XrayR/service/controller/controller.go:50 +0x14c
xrayr_1  | github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00051ec80)
xrayr_1  |   github.com/XrayR-project/XrayR/panel/panel.go:172 +0x543
xrayr_1  | main.main()
xrayr_1  |   github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed

**Comment by thank243** [comment]
使用`curl`拉取下v2b的下发文件。自行脱敏。

**Comment by crackair** [comment]
@aiastia 提供节点相关配置截图

**Comment by aiastia** [comment]
更新1.5.5 用不了 
目前退回了 1.5.4  重启节点后一切正常。
 我用的docker config 配置如下。（删除敏感信息了）

````
Log:
  Level: debug # Log level: none, error, warning, info, debug 
  AccessPath: # ./access.Log
  ErrorPath: # ./error.log
DnsConfigPath: /etc/XrayR/dns.json # ./dns.json Path to dns config
ConnetionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 10 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB 
Nodes:
  -
     PanelType: "V2board" # Panel type: SSpanel, V2board
     ApiConfig:
       ApiHost: ""
       ApiKey: ""
       NodeID: 1
       NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan
       Timeout: 120 # Timeout for the api request
       EnableVless: false # Enable Vless for V2ray Type
       EnableXTLS: false # Enable XTLS for V2ray and Trojan
       SpeedLimit: 0 # Mbps, Local settings will replace remote settings
       DeviceLimit: 0 # Local settings will replace remote settings
     ControllerConfig:
       ListenIP: 0.0.0.0 # IP address you want to listen
       UpdatePeriodic: 120 # Time to update the nodeinfo, how many sec.
       EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
       CertConfig:
         CertMode: dns # Option about how to get certificate: none, file, http, dns
         CertDomain: "" # Domain to cert
         Provider: cloudflare # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
         Email: 
         DNSEnv: # DNS ENV option used by DNS provider
           CF_DNS_API_TOKEN: 

````

![image](https://user-images.githubusercontent.com/19776350/148552124-5b5ef8dc-d0fb-4154-a8d9-94d0cf0f7c47.png)
